# Generated by Django 6.0.2 on 2026-02-06 03:26

import cv.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datospersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=200, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('perfilactivo', models.BooleanField(default=False)),
                ('permitir_impresion', models.BooleanField(default=False)),
                ('apellidos', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]+$')])),
                ('nombres', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]+$')])),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fechanacimiento', models.DateField(validators=[cv.models.validar_fecha_no_futura])),
                ('numerocedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('sexo', models.CharField(blank=True, choices=[('H', 'H'), ('M', 'M')], max_length=1, null=True)),
                ('estadocivil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión libre')], max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, choices=[('A', 'Tipo A'), ('A1', 'Tipo A1'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('C1', 'Tipo C1'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('F', 'Tipo F'), ('G', 'Tipo G')], max_length=10, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('telefonofijo', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('direcciontrabajo', models.CharField(blank=True, max_length=120, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=120, null=True)),
                ('sitioweb', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DATOSPERSONALES',
            },
        ),
        migrations.CreateModel(
            name='Cursosrealizados',
            fields=[
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('certificado_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/')),
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=120)),
                ('fechainicio', models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura])),
                ('fechafin', models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura])),
                ('totalhoras', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcioncurso', models.CharField(blank=True, max_length=200, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=120, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=120, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.EmailValidator()])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'CURSOSREALIZADOS',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'nombrecurso', 'fechainicio', 'fechafin'), name='uq_curso_perfil_nombre_fechas')],
            },
        ),
        migrations.CreateModel(
            name='Experiencialaboral',
            fields=[
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('certificado_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/')),
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombrempresa', models.CharField(max_length=120)),
                ('cargodesempenado', models.CharField(max_length=120)),
                ('fechainicio', models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura])),
                ('fechafin', models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura])),
                ('responsabilidades', models.TextField(blank=True, null=True)),
                ('direccionempresa', models.CharField(blank=True, max_length=150, null=True)),
                ('telefonoempresa', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('emailempresa', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.EmailValidator()])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=200, null=True)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('sitiowebempresa', models.URLField(blank=True, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'EXPERIENCIALABORAL',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'nombrempresa', 'cargodesempenado', 'fechainicio', 'fechafin'), name='uq_exp_perfil_empresa_cargo_fechas')],
            },
        ),
        migrations.CreateModel(
            name='Productosacademicos',
            fields=[
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('certificado_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/')),
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=120)),
                ('clasificador', models.CharField(choices=[('ARTICULO', 'Artículo'), ('TESIS', 'Tesis'), ('INVESTIGACION', 'Investigación'), ('PROYECTO', 'Proyecto'), ('PONENCIA', 'Ponencia'), ('POSTER', 'Póster'), ('LIBRO', 'Libro / Capítulo'), ('ENSAYO', 'Ensayo'), ('INFORME', 'Informe'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('imagenproducto', models.ImageField(blank=True, null=True, upload_to='productos/academicos/')),
                ('rutaimagen', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSACADEMICOS',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'nombreproducto', 'clasificador'), name='uq_prodacad_perfil_nombre_clasif')],
            },
        ),
        migrations.CreateModel(
            name='Productoslaborales',
            fields=[
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('certificado_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/')),
                ('idproductolaboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=120)),
                ('fechaproducto', models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('imagenproducto', models.ImageField(blank=True, null=True, upload_to='productos/laborales/')),
                ('rutaimagen', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSLABORALES',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'nombreproducto', 'fechaproducto'), name='uq_prodlab_perfil_nombre_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('certificado_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/')),
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=20)),
                ('fechareconocimiento', models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura])),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'RECONOCIMIENTOS',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tiporeconocimiento', 'fechareconocimiento', 'entidadpatrocinadora'), name='uq_recon_perfil_tipo_fecha_entidad')],
            },
        ),
        migrations.CreateModel(
            name='Ventagarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=120)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(validators=[cv.models.validar_fecha_no_futura])),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'VENTAGARAGE',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'nombreproducto', 'fecha'), name='uq_venta_perfil_producto_fecha')],
            },
        ),
    ]
